title: Defund Climate Chaos
email:
tagline: "#StopTheMoney"
description: Without money, oil and gas companies  will not function. So lets stop the money flowing.
url: 'https://defundclimatechaos.uk'
permalink: pretty
background_color: "#FFF0E3"
logo: /assets/logo_long.svg
logo_light: /assets/logo_light.svg
logo_square: /assets/logo.svg
invert_brand_text: true
invert_accent_text: true
instagram:
twitter:
facebook:

nav_links:
  - url: "/#act"
    title: Act

future: true
# google_analytics: G-LR3ETXLRXT

copyright_notice: ''
collections:
  posts:
    permalink: "/stories/:title/"
  faqs:
    output: true
    permalink: "/faqs/:title/"
  trainings:
    output: true
defaults:
  - scope:
      path: google2b8ceaa38de54302.html
    values:
      sitemap: false
  - scope:
      path: admin/index.html
    values:
      sitemap: false

airtable:
  faqs:
    app:   app9apHbqOifmolTX
    table: tblJHaJ0bOGLiXs9Q
    view:  viwMR1I5H8JtypsIR
  resources:
    app:   app9apHbqOifmolTX
    table: tblGAJiIeFlD6PxNI
    view:  viwBQ8s617LvMdODw
  partners:
    app:   app9apHbqOifmolTX
    table: tbl3erzSL6dZfNkZi
    view:  viwcwyl4ejOXEUaS0
    fields:
      - Name
      - Website
      - Logo
  posts:
    app:   app9apHbqOifmolTX
    table: tbluLxNnxcePzY4iN
    view:  viwlLkcEaTIKV99bx
    fields:
      - Content
      - Title
      - Date
      - Summary
      - Image
    collection:
      slug: title
      layout: post
      content: content
  trainings:
    app:   app9apHbqOifmolTX
    table: tblr8deZvWPtDpT8z
    view: viwmoConiofljNaYn
    fields:
      - Content
      - Title
      - Summary
      - Image
      - Booking link
      - Date
      - End date
    collection:
      slug: title
      layout: event
      content: content


map:
  lat: # 50
  lng:
plugins:
- jekyll-feed
- jekyll-liquify
- jekyll-leaflet
