title: Defund Climate Chaos
email:
tagline: "#StopTheMoney"
description: Without money, oil and gas companies  will not function. So lets stop the money flowing.
url: 'https://joe.irving.me.uk'
permalink: pretty
background_color: "#FFF0E3"
logo: /assets/logo_long.svg
logo_light: /assets/logo_light.svg
logo_square: /assets/logo.svg
invert_brand_text: true
invert_accent_text: true
instagram:
twitter: \#
facebook:

copyright_notice: ''
collections:
  posts:
    permalink: "/news/:title/"
  faqs:
    output: true
    permalink: "/faqs/:title/"
defaults:
- scope:
    path: google1c899b51019de383.html
  values:
    sitemap: false
- scope:
    path: admin/index.html
  values:
    sitemap: false
map:
  lat: # 50
  lng:
plugins:
- jekyll-feed
- jekyll-liquify
- jekyll-leaflet
