---
title: Defund Climate Chaos
email: fossilfinance@defundclimatechaos.uk
tagline: Turn off the money pipeline to fossil fuels. Now.
description: Join a global day of action on 29th October to demand UK banks and investors
  defund climate chaos immediately
url: https://defundclimatechaos.uk
theme: jekyll-theme-chaos
permalink: pretty
background_color: "#FFF0E3"
logo: "/assets/logo_long_uncondenced.svg"
logo_light: "/assets/logo_light.svg"
logo_square: "/assets/logo.svg"
invert_brand_text: true
invert_accent_text: true
instagram: ''
twitter: ''
facebook: ''
counter: 29-Oct-2021 9am
timezone: Europe/London
future: true
copyright_notice: With thanks to [David Gundry](https://www.davidgundry.co.uk/) for
  the base theme.
defaults:
- scope:
    path: google2b8ceaa38de54302.html
  values:
    sitemap: false
- scope:
    path: admin/index.html
  values:
    sitemap: false
collections:
  posts:
    permalink: "/stories/:title/"
  faqs:
    output: true
    permalink: "/faqs/:title/"
  trainings:
    output: true
  actions:
    output: true
  resources:
    output: true
  templates:
    output: false
airtable:
  faqs:
    app: app9apHbqOifmolTX
    table: tblJHaJ0bOGLiXs9Q
    view: viwnb7uvg8ljkiqIl
  resources:
    app: app9apHbqOifmolTX
    table: tblGAJiIeFlD6PxNI
    view: viwBQ8s617LvMdODw
    combine: true
  partners:
    app: app9apHbqOifmolTX
    table: tbl3erzSL6dZfNkZi
    view: viwcwyl4ejOXEUaS0
    fields:
    - Title
    - URL
    - Image
    - Summary
    - Invert Logo Colour
  trainings:
    app: app9apHbqOifmolTX
    table: tblr8deZvWPtDpT8z
    view: viwmoConiofljNaYn
    fields:
    - Content
    - Title
    - Summary
    - Image
    - Booking link
    - Start Date
    - End date
    collection:
      slug: title
      layout: event
      content: content
jekyll_get_json:
- data: events
  json: https://raw.githubusercontent.com/tippingpointuk/an-event-campaign-map/master/events.json
plugins:
- jekyll-get-json
- jekyll-airtable-import
nav_links: []
map:
  lat: ''
  lng: ''
