---
title: Defund Climate Chaos
email: fossilfinance@defundclimatechaos.uk
tagline: Turn off the money pipeline to fossil fuels. Now.
description: 'UK banks, investors and insurers are pumping billions of pounds into
  fossilfuels that worsen the climate crisis. People around the world are rising up
  to demand that governments and corporations #DefundClimateChaos, pay Climate Reparations
  and fund a Global Just Transition.'
url: https://defundclimatechaos.uk
theme: jekyll-theme-chaos
permalink: pretty
background_color: "#FFF0E3"
logo: "/assets/logo.svg"
logo_light: "/assets/logo_light.svg"
logo_square: "/assets/logo.svg"
invert_brand_text: true
invert_accent_text: true
instagram: 'People around the world are rising up to demand that governments and corporations
  #DefundClimateChaos, pay #ClimateReparations and fund a #GlobalJustTransition Take
  Action www.defundclimatechaos.uk'
twitter: 'People around the world are rising up to demand that governments and corporations
  #DefundClimateChaos, pay #ClimateReparations and fund a #GlobalJustTransition Take
  Action www.defundclimatechaos.uk'
facebook: 'People around the world are rising up to demand that governments and corporations
  #DefundClimateChaos, pay #ClimateReparations and fund a #GlobalJustTransition Take
  Action www.defundclimatechaos.uk'
counter: ''
timezone: Europe/London
future: true
copyright_notice: With thanks to [David Gundry](https://www.davidgundry.co.uk/) for
  the base theme.
defaults:
- scope:
    path: google2b8ceaa38de54302.html
  values:
    sitemap: false
- scope:
    path: admin/index.html
  values:
    sitemap: false
collections:
  posts:
    permalink: "/stories/:title/"
  faqs:
    output: true
    permalink: "/faqs/:title/"
  trainings:
    output: true
  actions:
    output: true
  resources:
    output: true
    permalink: "/resources/:slug/"
  templates:
    output: false
  banks:
    output: true
  digital_actions:
    output: true
    permalink: "/act/:slug/"
  briefings:
    output: true
airtable:
  faqs:
    app: app9apHbqOifmolTX
    table: tblJHaJ0bOGLiXs9Q
    view: viwAHX8hOvaGE8x2A
  agms:
    app: app9apHbqOifmolTX
    table: tblujlVLnyB08vGnO
    view: viwmYewgLWxVUnR9P
    fields:
    - Title
    - Date
    - Description
    - Image
    - URL
    - Actions
    - Address
  resources:
    app: app9apHbqOifmolTX
    table: tblGAJiIeFlD6PxNI
    view: viwBQ8s617LvMdODw
    combine: true
  briefings:
    app: app9apHbqOifmolTX
    table: tblGAJiIeFlD6PxNI
    view: viwU1ycAZj7RWLyzf
    collection:
      slug: briefings
      layout: briefing
      content: content
    fields:
      - title
      - Motion
      - Video
      - YouTube ID
      - description
      - Content
      - Image
      - Tags
      - Category
      - Google Doc ID
  partners:
    app: app9apHbqOifmolTX
    table: tbl3erzSL6dZfNkZi
    view: viwcwyl4ejOXEUaS0
    fields:
    - Title
    - URL
    - Image
    - Summary
    - Invert Logo Colour
  actions:
    app: app9apHbqOifmolTX
    table: tblVEvKXgQXEwyNKh
    view: viwQUUUl3inwcW4A5
    fields:
    - Title
    - AGM
    - Booking link
    - Start date
    - End date
    - Slug
    - Address
    - Latitude
    - Longitude
    - Content
    - Future
    - Type
    - Image
    collection:
      slug: slug
      layout: an-event
      content: content
  trainings:
    app: app9apHbqOifmolTX
    table: tblVEvKXgQXEwyNKh
    view: viwG1BYPfTrElrkwC
    fields:
    - Content
    - Title
    - Summary
    - Image
    - Booking link
    - Start Date
    - End date
    collection:
      slug: title
      layout: event
      content: content
  campaigns:
    app: app9apHbqOifmolTX
    table: tbllOtliZXqlwJavx
    view: viw3ts1xG41SMu4zO
    fields:
      - Title
      - Description
      - Link
      - Image
      - Status

action_network:
  key: ENV_AN_API_KEY
  actions: false
  import:
    - name: events
      include_event_campaigns: false
      layout: an-page-2
    - name: petitions
      layout: an-page-2
    - name: forms
      layout: an-page-2
    - name: campaigns
      layout: an-page-2
    - name: advocacy_campaigns
      layout: an-page-2

plugins:
- jekyll-airtable-import
- jekyll-menus
- jekyll-action-network
nav_links: []
google_analytics: G-LR3ETXLRXT
map:
  lat: ''
  lng: ''
exclude:
- api
- .forestry
- .git
include:
- _redirects
jekyll_get_json: []
