---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: ''
sections:
- type: document
  path: index.md
  label: Home Page
- type: jekyll-pages
  label: All Pages
  create: all
- type: heading
  label: Collections
- type: directory
  path: _resources
  label: Resources
  create: all
  match: "**/*"
  templates:
  - resource
- type: jekyll-posts
  label: Stories
  create: all
  templates:
  - stories
- type: heading
  label: Config
- type: document
  path: _config.yml
  label: Main Site Config
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - AIRTABLE_API_KEY=keyd5v8cFVspwAV6N
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site --trace
